import { Character } from './character';

export const CHARACTERS: Character[] = [
  { id: 1, name: 'Luke Skywalker', birthYear: '19BBY', species: 'Human',height: '172cm',mass: '77kg',gender: 'Male',hairColor: 'Blond',skinColor: 'Fair',homeWorld: 'Tatooine',comments: ''},
  { id: 2, name: 'C-3PO', birthYear: '112BBY', species: 'Droid',height: '167cm',mass: '75kg',gender: 'n/a',hairColor: 'n/a',skinColor: 'Gold',homeWorld: 'Tatooine',comments: ''},
  { id: 3, name: 'R2-D2', birthYear: '33BBY', species: 'Droid',height: '96cm',mass: '32kg',gender: 'n/a',hairColor: 'n/a',skinColor: 'White,Blue',homeWorld: 'Naboo',comments: ''},   
  { id: 4, name: 'Darth Vader', birthYear: '41.9BBY', species: 'Human',height: '202cm',mass: '136kg',gender: 'Male',hairColor: 'None',skinColor: 'White',homeWorld: 'Tatooine',comments: ''},
  { id: 5, name: 'Leia Organa', birthYear: '19BBY', species: 'Human',height: '150cm',mass: '49kg',gender: 'Female',hairColor: 'Brown',skinColor: 'Light',homeWorld: 'Alderaan',comments: ''},
  { id: 6, name: 'Owen Lars', birthYear: 'Unknown', species: 'Droid',height: '97cm',mass: '32kg',gender: 'n/a',hairColor: 'n/a',skinColor: 'White, Red',homeWorld: 'Tatooine',comments: ''},
  { id: 7, name: 'Beru Whitesun Lars', birthYear: '47BBY', species: 'Human',height: '165cm',mass: '75kg',gender: 'Female',hairColor: 'Brown',skinColor: 'Light',homeWorld: 'Tatooine',comments: ''},
  { id: 8, name: 'R5-D4', birthYear: '52BBY', species: 'Human',height: '178cm',mass: '120kg',gender: 'Male',hairColor: 'Brown, Grey',skinColor: 'Light',homeWorld: 'Tatooine',comments: ''},
  { id: 9, name: 'Biggs Darklighter', birthYear: '24BBY', species: 'Human',height: '183cm',mass: '84kg',gender: 'Male',hairColor: 'Black',skinColor: 'Light',homeWorld: 'Tatooine',comments: ''},
  { id: 10, name: 'Obi-Wan Kenobi', birthYear: '57BBY', species: 'Human',height: '182cm',mass: '77kg',gender: 'Male',hairColor: 'Auburn, White',skinColor: 'Fair',homeWorld: 'Stewjon',comments: ''},
  { id: 11, name: 'Anakin Skywalker', birthYear: '41.9BBY', species: 'Human',height: '188cm',mass: '84kg',gender: 'Male',hairColor: 'Blond',skinColor: 'Fair',homeWorld: 'Tatooine',comments: ''},
  { id: 12, name: 'Wilhuff Tarkin', birthYear: '64BBY', species: 'Human',height: '180cm',mass: 'Unknown',gender: 'Male',hairColor: 'Auburn, Grey',skinColor: 'Fair',homeWorld: 'Eriadu',comments: ''},
  { id: 13, name: 'Chewbacca', birthYear: '200BBY', species: 'Wookiee',height: '228cm',mass: '112kg',gender: 'Male',hairColor: 'Brown',skinColor: 'Unknown',homeWorld: 'Kashyyyk',comments: ''},
  { id: 14, name: 'Han Solo', birthYear: '29BBY', species: 'Human',height: '180cm',mass: '80kg',gender: 'Male',hairColor: 'Brown',skinColor: 'Fair',homeWorld: 'Corellia',comments: ''},
  { id: 15, name: 'Greedo', birthYear: '44BBY', species: 'Rodian',height: '173cm',mass: '74kg',gender: 'Male',hairColor: 'n/a',skinColor: 'Green',homeWorld: 'Rodia',comments: ''},
  { id: 16, name: 'Jabba Desilijic Tiure', birthYear: '600BBY', species: 'Hutt',height: '175cm',mass: '1358kg',gender: 'Hermaphrodite',hairColor: 'n/a',skinColor: 'Green-tan, Brown',homeWorld: 'Nal Hutta',comments: ''},
  { id: 17, name: 'Wedge Antilles', birthYear: '21BBY', species: 'Human',height: '170cm',mass: '77kg',gender: 'Male',hairColor: 'Brown',skinColor: 'Fair',homeWorld: 'Corellia',comments: ''},
  { id: 18, name: 'Jek Tono Porkins', birthYear: 'Unknown', species: 'Human',height: '180cm',mass: '110kg',gender: 'Male',hairColor: 'Brown',skinColor: 'Fair',homeWorld: 'Bestine IV',comments: ''},
  { id: 19, name: 'Yoda', birthYear: '896BBY', species: 'Yodas Species',height: '66cm',mass: '17kg',gender: 'Male',hairColor: 'White',skinColor: 'Green',homeWorld: 'Unknown',comments: ''},
  { id: 20, name: 'Palpatine', birthYear: '82BBY', species: 'Human',height: '170cm',mass: '75kg',gender: 'Male',hairColor: 'Grey',skinColor: 'Pale',homeWorld: 'Naboo',comments: ''},
  { id: 21, name: 'Boba Fett', birthYear: '31.5BBY', species: 'Human',height: '183cm',mass: '78.2kg',gender: 'Male',hairColor: 'Black',skinColor: 'Fair',homeWorld: 'Kamino',comments: ''},
  { id: 22, name: 'IG-88', birthYear: '15BBY', species: 'Droid',height: '200cm',mass: '140kg',gender: 'None',hairColor: 'None',skinColor: 'Metal',homeWorld: 'Unknown',comments: ''},
  { id: 23, name: 'Bossk', birthYear: '53BBY', species: 'Trandoshan',height: '190cm',mass: '113kg',gender: 'Male',hairColor: 'None',skinColor: 'Green',homeWorld: 'Trandosha',comments: ''},
  { id: 24, name: 'Lando Calrissian', birthYear: '31BBY', species: 'Human',height: '177cm',mass: '79kg',gender: 'Male',hairColor: 'Black',skinColor: 'Dark',homeWorld: 'Socorro',comments: ''},
  { id: 25, name: 'Lobot', birthYear: '37BBY', species: 'Human',height: '175cm',mass: '79kg',gender: 'Male',hairColor: 'None',skinColor: 'Light',homeWorld: 'Bespin',comments: ''},
  { id: 26, name: 'Ackbar', birthYear: '41BBY', species: 'Mon Calamari',height: '180cm',mass: '83kg',gender: 'Male',hairColor: 'None',skinColor: 'Brown Mottle',homeWorld: 'Mon Cala',comments: ''},
  { id: 27, name: 'Mon Mothma', birthYear: '48BBY', species: 'Human',height: '150cm',mass: 'Unknown',gender: 'Female',hairColor: 'Auburn',skinColor: 'Fair',homeWorld: 'Chandrila',comments: ''},
  { id: 28, name: 'Arvel Crynyd', birthYear: 'Unknown', species: 'Human',height: 'Unknown',mass: 'Unknown',gender: 'Male',hairColor: 'Brown',skinColor: 'Fair',homeWorld: 'Unknown',comments: ''},
  { id: 29, name: 'Wicket Systri Warrick', birthYear: '8BBY', species: 'Ewok',height: '88cm',mass: '20kg',gender: 'Male',hairColor: 'Brown',skinColor: 'Brown',homeWorld: 'Endor',comments: ''},
  { id: 30, name: 'Nien Nunb', birthYear: 'Unknown', species: 'Sullustan',height: '160cm',mass: '68kg',gender: 'Male',hairColor: 'None',skinColor: 'Grey',homeWorld: 'Sullust',comments: ''},
  { id: 31, name: 'Qui-Gon Jinn', birthYear: '92BBY', species: 'Human',height: '193cm',mass: '89kg',gender: 'Male',hairColor: 'Brown',skinColor: 'Fair',homeWorld: 'Unknown',comments: ''},
  { id: 32, name: 'Nute Gunray', birthYear: 'Unknown', species: 'Neimodian',height: '191cm',mass: '90kg',gender: 'Male',hairColor: 'None',skinColor: 'Mottled Green',homeWorld: 'Cato Neimoidia',comments: ''},
  { id: 33, name: 'Finis Valorum', birthYear: '91BBY', species: 'Human',height: '170cm',mass: 'Unknown',gender: 'Male',hairColor: 'Blond',skinColor: 'Fair',homeWorld: 'Coruscant',comments: ''},
  { id: 34, name: 'Jar Jar Binks', birthYear: '52BBY', species: 'Gungan',height: '196cm',mass: '66kg',gender: 'Male',hairColor: 'None',skinColor: 'Orange',homeWorld: 'Naboo',comments: ''},
  { id: 35, name: 'Roos Tarpals', birthYear: 'Unknown', species: 'Gungan',height: '224cm',mass: '82kg',gender: 'Male',hairColor: 'None',skinColor: 'Grey',homeWorld: 'Naboo',comments: ''},
  { id: 36, name: 'Rugor Nass', birthYear: 'Unknown', species: 'Gungan',height: '206cm',mass: 'Unknown',gender: 'Male',hairColor: 'None',skinColor: 'Green',homeWorld: 'Naboo',comments: ''},
  { id: 37, name: 'Ric Olié', birthYear: 'Unknown', species: 'Unknown',height: '183cm',mass: 'Unknown',gender: 'Male',hairColor: 'Brown',skinColor: 'Fair',homeWorld: 'Naboo',comments: ''},
  { id: 38, name: 'Watto', birthYear: 'Unknown', species: 'Toydarian',height: '137cm',mass: 'Unknown',gender: 'Male',hairColor: 'Black',skinColor: 'Blue, Grey',homeWorld: 'Toydaria',comments: ''},
  { id: 39, name: 'Sebulba', birthYear: 'Unknown', species: 'Dug',height: '112cm',mass: '40kg',gender: 'Male',hairColor: 'None',skinColor: 'Grey, Red',homeWorld: 'Malastare',comments: ''},
  { id: 40, name: 'Quarsh Panaka', birthYear: '62BBY', species: 'Unknown',height: '183cm',mass: 'Unknown',gender: 'Male',hairColor: 'Black',skinColor: 'Dark',homeWorld: 'Naboo',comments: ''},
  { id: 41, name: 'Shmi Skywalker', birthYear: '72BBY', species: 'Human',height: '163cm',mass: 'Unknown',gender: 'Female',hairColor: 'Black',skinColor: 'Fair',homeWorld: 'Tatooine',comments: ''},
  { id: 42, name: 'Darth Maul', birthYear: '54BBY', species: 'Zabrak',height: '175cm',mass: '80kg',gender: 'Male',hairColor: 'None',skinColor: 'Red',homeWorld: 'Naboo',comments: ''},
  { id: 43, name: 'Bib Fortuna', birthYear: 'Unknown', species: 'Twilek',height: '180cm',mass: 'Unknown',gender: 'Male',hairColor: 'None',skinColor: 'Pale',homeWorld: 'Ryloth',comments: ''},
  { id: 44, name: 'Ayla Secura', birthYear: '48BBY', species: 'Twilek',height: '178cm',mass: '55kg',gender: 'Female',hairColor: 'None',skinColor: 'Blue',homeWorld: 'Ryloth',comments: ''},
  { id: 45, name: 'Dud Bolt', birthYear: 'Unknown', species: 'Vulptereen',height: '94cm',mass: '45kg',gender: 'Male',hairColor: 'None',skinColor: 'Blue, Grey',homeWorld: 'Naboo',comments: ''},
  { id: 46, name: 'Gasgano', birthYear: 'Unknown', species: 'Xexto',height: '122cm',mass: 'Unknown',gender: 'Male',hairColor: 'None',skinColor: 'White, Blue',homeWorld: 'Troiken',comments: ''},
  { id: 47, name: 'Ben Quadinaros', birthYear: 'Unknown', species: 'Toong',height: '163cm',mass: '65kg',gender: 'Male',hairColor: 'None',skinColor: 'Grey, Green, Yellow',homeWorld: 'Tund',comments: ''},
  { id: 48, name: 'Mace Windu', birthYear: '72BBY', species: 'Human',height: '188cm',mass: '84kg',gender: 'Male',hairColor: 'None',skinColor: 'Dark',homeWorld: 'Haruun Kal',comments: ''},
  { id: 49, name: 'Ki-Adi-Mundi', birthYear: '92BBY', species: 'Cerean',height: '198cm',mass: '82kg',gender: 'Male',hairColor: 'White',skinColor: 'Pale',homeWorld: 'Cerea',comments: ''},
  { id: 50, name: 'Kit Fisto', birthYear: 'Unknown', species: 'Nautolan',height: '196cm',mass: '87kg',gender: 'Male',hairColor: 'None',skinColor: 'Green',homeWorld: 'Glee Anselm',comments: ''},
  {id: 51, name: 'Mace Windu', birthYear: '72BBY', species: 'Human', height: '188cm', mass: '84kg', gender: 'Male', hairColor: 'None', skinColor: 'Dark', homeWorld: 'Haruun Kal', comments: ""},
  {id: 52, name: 'Ki-Adi-Mundi', birthYear: '92BBY', species: 'Cerean', height: '198cm', mass: '82kg', gender: 'Male', hairColor: 'White', skinColor: 'Pale', homeWorld: 'Cerea', comments: ""},
  {id: 53, name: 'Kit Fisto', birthYear: 'Unknown', species: 'Nautolan', height: '196cm', mass: '87kg', gender: 'Male', hairColor: 'None', skinColor: 'Green', homeWorld: 'Glee Anselm', comments: ""},
  {id: 54, name: 'Eeth Koth', birthYear: 'Unknown', species: 'Zabrak', height: '171cm', mass: 'Unknown', gender: 'Male', hairColor: 'Black', skinColor: 'Brown', homeWorld: 'Iridonia', comments: ''},
  {id: 55, name: 'Adi Gallia', birthYear: 'Unknown', species: 'Tholothian', height: '184cm', mass: '50kg', gender: 'Female', hairColor: 'None', skinColor: 'Dark', homeWorld: 'Coruscant', comments: ''},
  {id: 56, name: 'Saesee Tiin', birthYear: 'Unknown', species: 'Iktotchi', height: '188cm', mass: 'Unknown', gender: 'Male', hairColor: 'None', skinColor: 'Pale', homeWorld: 'Iktotch', comments: ''},
  {id: 57, name: 'Yarael Poof', birthYear: 'Unknown', species: 'Quermian', height: '264cm', mass: 'Unknown', gender: 'Male', hairColor: 'None', skinColor: 'White', homeWorld: 'Quermia', comments: ''},
  {id: 58, name: 'Plo Koon', birthYear: '22BBY', species: 'Kel Dor', height: '188cm', mass: '80kg', gender: 'Male', hairColor: 'None', skinColor: 'Orange', homeWorld: 'Dorin', comments: ''},
  {id: 59, name: 'Mas Amedda', birthYear: 'Unknown', species: 'Chagrian', height: '196cm', mass: 'Unknown', gender: 'Male', hairColor: 'None', skinColor: 'Blue', homeWorld: 'Champala', comments: ''},
  {id: 60, name: 'Gregar Typho', birthYear: 'Unknown', species: 'Human', height: '185cm', mass: '85kg', gender: 'Male', hairColor: 'Black', skinColor: 'Dark', homeWorld: 'Naboo', comments: ''},
  {id: 61, name: 'Cordé', birthYear: 'Unknown', species: 'Human', height: '157cm', mass: 'Unknown', gender: 'Female', hairColor: 'Brown', skinColor: 'Light', homeWorld: 'Naboo', comments: ''},
  {id: 62, name: 'Cliegg Lars', birthYear: '82BBY', species: 'Human', height: '183cm', mass: 'Unknown', gender: 'Male', hairColor: 'Brown', skinColor: 'Fair', homeWorld: 'Tatooine', comments: ''},
  {id: 63, name: 'Poggle The Lesser', birthYear: 'Unknown', species: 'Geonosian', height: '183cm', mass: '80kg', gender: 'Male', hairColor: 'None', skinColor: 'Green', homeWorld: 'Geonosis', comments: ''},
  {id: 64, name: 'Luminara Unduli', birthYear: '58BBY', species: 'Mirialan', height: '170cm', mass: '56.2kg', gender: 'Female', hairColor: 'Black', skinColor: 'Yellow', homeWorld: 'Mirial', comments: ''},
  {id: 65, name: 'Barriss Offee', birthYear: '40BBY', species: 'Mirialan', height: '166cm', mass: '50kg', gender: 'Female', hairColor: 'Black', skinColor: 'Yellow', homeWorld: 'Mirial', comments: ''},
  {id: 66, name: 'Dormé', birthYear: 'Unknown', species: 'Human', height: '165cm', mass: 'Unknown', gender: 'Female', hairColor: 'Brown', skinColor: 'Light', homeWorld: 'Naboo', comments: ''},
  {id: 67, name: 'Dooku', birthYear: '102BBY', species: 'Human', height: '193cm', mass: '80kg', gender: 'Male', hairColor: 'White', skinColor: 'Fair', homeWorld: 'Serenno', comments: ''},
  {id: 68, name: 'Bail Prestor Organa', birthYear: '67BBY', species: 'Human', height: '191cm', mass: 'Unknown', gender: 'Male', hairColor: 'Black', skinColor: 'Tan', homeWorld: 'Alderaan', comments: ''},
  {id: 69, name: 'Jango Fett', birthYear: '66BBY', species: 'Human', height: '183cm', mass: '79kg', gender: 'Male', hairColor: 'Black', skinColor: 'Tan', homeWorld: 'Concord Dawn', comments: ''},
  {id: 70, name: 'Zam Wesell', birthYear: 'Unknown', species: 'Clawdite', height: '168cm', mass: '55kg', gender: 'Female', hairColor: 'Blonde', skinColor: 'Fair, Green, Yellow', homeWorld: 'Zolan', comments: ''},
  {id: 71, name: 'Dexter Jettster', birthYear: 'Unknown', species: 'Besalisk', height: '198cm', mass: '102kg', gender: 'Male', hairColor: 'None', skinColor: 'Brown', homeWorld: 'Ojom', comments: ''},
  {id: 72, name: 'Lama Su', birthYear: 'Unknown', species: 'Kaminoan', height: '229cm', mass: '88kg', gender: 'Male', hairColor: 'None', skinColor: 'Grey', homeWorld: 'Kamino', comments: ''},
  {id: 73, name: 'Taun We', birthYear: 'Unknown', species: 'Kaminoan', height: '213cm', mass: 'Unknown', gender: 'Female', hairColor: 'None', skinColor: 'Grey', homeWorld: 'Kamino', comments: ''},
  {id: 74, name: 'Jocasta Nu', birthYear: 'Unknown', species: 'Human', height: '167cm', mass: 'Unknown', gender: 'Female', hairColor: 'White', skinColor: 'Fair', homeWorld: 'Coruscant', comments: ''},
  {id: 75, name: 'R4-P17', birthYear: 'Unknown', species: 'Unknown', height: '96cm', mass: 'Unknown', gender: 'Female', hairColor: 'None', skinColor: 'Silver, Red', homeWorld: 'Unknown', comments: ''},
  {id: 76, name: 'Wat Tambor', birthYear: 'Unknown', species: 'Skakoan', height: '193cm', mass: '48kg', gender: 'Male', hairColor: 'None', skinColor: 'Green, Grey', homeWorld: 'Skako', comments: ''},
  {id: 77, name: 'San Hill', birthYear: 'Unknown', species: 'Muun', height: '191cm', mass: 'Unknown', gender: 'Male', hairColor: 'None', skinColor: 'Grey', homeWorld: 'Muunilinst', comments: ''},
  {id: 78, name: 'Shaak Ti', birthYear: 'Unknown', species: 'Togruta', height: '178cm', mass: '57kg', gender: 'Female', hairColor: 'None', skinColor: 'Red, Blue, White', homeWorld: 'Shili', comments: ''},
  {id: 79, name: 'Grievous', birthYear: 'Unknown', species: 'Kaleesh', height: '216cm', mass: '159kg', gender: 'Male', hairColor: 'None', skinColor: 'Brown, White', homeWorld: 'Kalee', comments: ''},
  {id: 80, name: 'Tarfful', birthYear: 'Unknown', species: 'Wookiee', height: '234cm', mass: '136kg', gender: 'Male', hairColor: 'Brown', skinColor: 'Brown', homeWorld: 'Kashyyyk', comments: ''},
  {id: 81, name: 'Raymus Antilles', birthYear: 'Unknown', species: 'Human', height: '188cm', mass: '79kg', gender: 'Male', hairColor: 'Brown', skinColor: 'Light', homeWorld: 'Alderaan', comments: ''},
  {id: 82, name: 'Sly Moore', birthYear: 'Unknown', species: 'Unknown', height: '178cm', mass: '48kg', gender: 'Female', hairColor: 'None', skinColor: 'Pale', homeWorld: 'Umbara', comments: ''},
  {id: 83, name: 'Tion Medon', birthYear: 'Unknown', species: "Pau'an", height: '206cm', mass: '80kg', gender: 'Male', hairColor: 'None', skinColor: 'Grey', homeWorld: 'Utapau', comments: ''},
  {id: 84, name: 'Finn', birthYear: 'Unknown', species: 'Human', height: 'Unknown', mass: 'Unknown', gender: 'Male', hairColor: 'Black', skinColor: 'Dark', homeWorld: 'Unknown', comments: ''},
  {id: 85, name: 'Rey', birthYear: 'Unknown', species: 'Human', height: 'Unknown', mass: 'Unknown', gender: 'Female', hairColor: 'Brown', skinColor: 'Light', homeWorld: 'Unknown', comments: ''},
  {id: 86, name: 'Poe Dameron', birthYear: 'Unknown', species: 'Human', height: 'Unknown', mass: 'Unknown', gender: 'Male', hairColor: 'Brown', skinColor: 'Light', homeWorld: 'Unknown', comments: ''},
  {id: 87, name: 'BB8', birthYear: 'Unknown', species: 'Droid', height: 'Unknown', mass: 'Unknown', gender: 'None', hairColor: 'None', skinColor: 'None', homeWorld: 'Unknown', comments: ''}
 ];